seed: 42
device: cuda
data:
  time_slice: 7
  patch_size: 256
  val_ratio: 0.2
  padding_multiple: 128
  h5_paths:
    input: "src/data/patches/input_patches.h5"
    target: "src/data/patches/target_patches.h5"
  paths:
   - 'data/amazon-1km/DTCB_acumul_area.npz'
   - 'data/amazon-1km/DTCB_area.npz'
   - 'data/amazon-1km/DTCB_count_areas.npz'
   - 'data/amazon-1km/DTCB_diff_area.npz'
   - 'data/amazon-1km/DTCB_seasonality_factor.npz'
training:
  batch_size: 8
  epochs: 1
  learning_rate: 0.001
early_stopping:
  patience: 10
  delta: 0.001
  verbose: true
model:
  deep_lab_v3:
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    in_channels: 5
    classes: 1
memory_record:
  enabled: false
  num_events: 100000
loss:
  weight: 5.0
  invalid_weight: 0.01
  pos_weight: 1.0
  soft_iou_weight: 1.0
metrics:
  threshold: 0.5
# Output file paths
save_paths:
  early_stopping: "checkpoints/early_stopping.pt"
  model: "checkpoints/trained_model.pth"
  plot: "plots/training_curves.png"
  history: "results/training_history.json"
  results: "results/evaluation_results.json"
  predictions: "results/predictions_3.h5"