seed: 42
device: cuda
data:
  time_slice: 7
  paths:
   - 'data/amazon-1km/DTCB_acumul_area.npz'
   - 'data/amazon-1km/DTCB_area.npz'
   - 'data/amazon-1km/DTCB_count_areas.npz'
   - 'data/amazon-1km/DTCB_diff_area.npz'
   - 'data/amazon-1km/DTCB_seasonality_factor.npz'
  val_ratio: 0.2
training:
  batch_size: 32
  epochs: 20
  learning_rate: 1e-3
early_stopping:
  patience: 10
  delta: 0.001
  path: "checkpoints/checkpoint.pt"
  verbose: true